name: sti_startnow
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  provider: ^6.1.4
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.9.0

  # FOR PDF SAVING AND OPENING
  pdf: ^3.11.3
  path_provider: ^2.1.5
  open_file: ^3.5.10
  permission_handler: ^12.0.0+1

  internet_connection_checker_plus: ^2.7.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - "assets/img/"
    - "assets/img/welcome_img/"
    - "assets/img/chatbot_profile/"
    - "assets/img/sign_in/"
    - "assets/img/navigation_icon/"
    - "assets/img/enrollment/"
    - "assets/img/enrollment_dashboard/"
    - "assets/img/enrollment_dashboard/courses_img/"
    - "assets/img/enrollment_dashboard/courses_img/specific/"

# For the App Icon
flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/icons/ios-icon.png"
  image_path_android: "assets/icons/android-icon.png"
  adaptive_icon_background: "assets/icons/android-icon-bg.png"
  adaptive_icon_foreground: "assets/icons/android-icon-fg.png"
  remove_alpha_ios: true